name: CI

on:
  push:
    branches: [publish, main]
  pull_request:

jobs:
  build-and-test:
    name: Build + test (lib)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Build library
        run: cargo build --lib -p goldworm
      - name: Test library
        run: cargo test --lib -p goldworm
